version: "3"
services:
  api:
    build: ./api
    ports:
      - "4567:4567"
    volumes:
      - "./api:/app"
    depends_on:
      - kvs
  mail:
    build: ./mail
    ports:
      - "25:25"
    volumes:
      - "./mail:/app"
    depends_on:
      - kvs
  kvs:
    build: ./redis
