version: "3"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - "./api:/app"
    depends_on:
      - kvs
  mail:
    build: ./mail
    ports:
      - "25:25"
    volumes:
      - "./mail:/app"
    depends_on:
      - kvs
  kvs:
    build: ./redis
